backend:
  name: git-gateway
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  ############### Single Pages ################
  - name: pages
    label: Pages
    files:
      ############### Homepage ################
      - name: home
        label: Home
        file: "/content/de/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - label: Hero Slider
            name: slider
            widget: object
            fields:
              - { label: "Enable Slider", name: "enable", widget: "boolean" }
              - name: slider_item
                label: Slider Items
                widget: list
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Subtitle", name: "subtitle", widget: "string" }
                  - { label: "Background Image", name: "bg_image", widget: "image" }
                  - { label: "Image", name: "image", widget: "image", required: false }
                  - { label: "Image Position", name: "image_position", widget: "select", options: ["left", "right", "center"] }
                  - label: Navigator
                    name: navigator
                    widget: object
                    fields:
                      - { label: "Label", name: "label", widget: "string" }
                      - { label: "Icon", name: "icon", widget: "string" }
                  - label: Buttons
                    name: buttons
                    widget: list
                    fields:
                      - { label: "Label", name: "label", widget: "string" }
                      - { label: "Style", name: "style", widget: "select", options: ["solid", "white"] }
                      - { label: "Link", name: "link", widget: "string" }
          - label: Service Types
            name: service
            widget: object
            fields:
              - { label: "Enable Services", name: "enable", widget: "boolean" }
              - name: services
                label: Services
                widget: object
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Subtitle", name: "subtitle", widget: "string" }
                  - { label: "Title Icon", name: "title_icon", widget: "string", hint: "Geben Sie den Namen des gewünschten Icons z. B. fa-tablet. Siehe https://fontawesome.com/v4.7.0/icons/"}
                  - label: Service Item
                    name: service_item
                    widget: list
                    fields:
                      - { label: "Name", name: "name", widget: "string" }
                      - { label: "Icon", name: "icon", widget: "string", hint: "Geben Sie den Namen des gewünschten Icons z. B. fa-tablet. Siehe https://fontawesome.com/v4.7.0/icons/" }
                      - { label: "Content", name: "content", widget: "string" }
            - label: Brands Logo Slider
            - name: brands_logo_slider
            - widget: object
            - fields:
                - label: Slider Item
                - name: slider_item
                - widget: list
                - fields:
                    - { label: "Name", name: "name", widget: "string" }
                    - { label: "Logo", name: "logo", widget: "image" }
                    - { label: "Link", name: "link", widget: "string" }
                


      ############### Impressum ################
      - name: impressum
        label: Impressum
        file: "/content/de/impressum.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }


  ############### Smartphone Hersteller ################
  - name: smartphone-hersteller
    label: Smartphone Hersteller
    folder: /content/de/smartphone-hersteller
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }

  ############### Smartphones ################
  - name: smartphones
    label: Smartphones
    folder: /content/de/smartphone
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Modell", name: "name", widget: "string" }
      - { label: "Hersteller", name: "manufacturer", widget: "select", options: ["Apple", "Asus", "Blackberry", "CAT", "Google", "HTC", "Huawei", "LG", "Motorola", "Nokia", "OnePlus", "Samsung", "Sony", "Xiaomi"] }
      - { label: "Services", name: "services", widget: "object", fields: [
          { label: "Analyse", name: "analyse", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string", required: false },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Wasserschaden", name: "wasserschaden", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Display", name: "display", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Lautsprecher", name: "lautsprecher", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "mikrofon", name: "mikrofon", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Hoermuschel", name: "hoermuschel", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Vorderkamera", name: "vorderkamera", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Hauptkamera", name: "hauptkamera", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Kameraglas", name: "kameraglas", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Backcover", name: "backcover", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Rahmen", name: "rahmen", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Akku", name: "akku", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Ladebuchse", name: "ladebuchse", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Buttons", name: "buttons", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Software Update", name: "software_update", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },          
        ]
      }

  
  ############### Tablet Hersteller ################
  - name: tablet-hersteller
    label: Tablet Hersteller
    folder: /content/de/tablet-hersteller
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
  ############### Tablets ################
  - name: tablets
    label: Tablets
    folder: /content/de/tablet
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Modell", name: "name", widget: "string" }
      - { label: "Hersteller", name: "manufacturer", widget: "select", options: ["Apple", "Google", "Microsoft", "Samsung"] }
      - { label: "Services", name: "services", widget: "object", fields: [
          { label: "Analyse", name: "analyse", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Wasserschaden", name: "wasserschaden", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Original Display", name: "original_display", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Glas Reparatur", name: "glas_reparatur", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Lautsprecher", name: "lautsprecher", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "mikrofon", name: "mikrofon", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Vorderkamera", name: "vorderkamera", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Hauptkamera", name: "hauptkamera", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Kameraglas", name: "kameraglas", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Backcover", name: "backcover", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Rahmen", name: "rahmen", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Akku", name: "akku", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Ladebuchse", name: "ladebuchse", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Buttons", name: "buttons", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Software Update", name: "software_update", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },          
        ]
      }