backend:
  name: git-gateway
  branch: main
media_folder: "static/content"
public_folder: "/content"
collections:
  ############### Single Pages ################
  - name: pages
    label: Pages
    files:
      ############### Homepage ################
      - name: home
        label: Home
        file: "/content/de/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
  ############### Slider ################
  - name: slider
    label: Home Slider
    files: "/content/de/_index.md"
      - name: slider
        label: Slider
        file:
        fields:
          - { label: "Enable", name: "enable", widget: "boolean", default: true }
          - { label: "Slider Items", name: "slider_item", widget: "list", fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "Subtitle", name: "subtitle", widget: "string" },
              { label: "Background Image", name: "bg_image", widget: "image" },
              { label: "Image", name: "image", widget: "image", required: false },
              { label: "Image Position", name: "image_position", widget: "select", options: ["left", "right", "center"] },
              { label: "Navigator Label", name: "navigator.label", widget: "string" },
              { label: "Navigator Icon", name: "navigator.icon", widget: "string" },
              { label: "Buttons", name: "buttons", widget: "list", fields: [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Style", name: "style", widget: "select", options: ["solid", "white"] },
                  { label: "Link", name: "link", widget: "string" }
                ]
              }
            ]
          }


  ############### Smartphone Hersteller ################
  - name: smartphone-hersteller
    label: Smartphone Hersteller
    folder: /content/smartphone-hersteller
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }

  ############### Smartphones ################
  - name: smartphones
    label: Smartphones
    folder: /content/de/smartphone
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Modell", name: "name", widget: "string" }
      - { label: "Hersteller", name: "manufacturer", widget: "string" }
      - { label: "Services", name: "services", widget: "object", fields: [
          { label: "Analyse", name: "analyse", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string", required: false },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Wasserschaden", name: "wasserschaden", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Display", name: "display", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Lautsprecher", name: "lautsprecher", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "mikrofon", name: "mikrofon", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Hoermuschel", name: "hoermuschel", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Vorderkamera", name: "vorderkamera", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Hauptkamera", name: "hauptkamera", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Kameraglas", name: "kameraglas", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Backcover", name: "backcover", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Rahmen", name: "rahmen", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Akku", name: "akku", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Ladebuchse", name: "ladebuchse", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Buttons", name: "buttons", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Software Update", name: "software_update", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },          
        ]
      }

  
  ############### Tablet Hersteller ################
  - name: tablet-hersteller
    label: Tablet Hersteller
    folder: /content/de/tablet-hersteller
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
  ############### Tablets ################
  - name: tablets
    label: Tablets
    folder: /content/de/tablet
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Modell", name: "name", widget: "string" }
      - { label: "Hersteller", name: "manufacturer", widget: "string" }
      - { label: "Services", name: "services", widget: "object", fields: [
          { label: "Analyse", name: "analyse", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Wasserschaden", name: "wasserschaden", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Original Display", name: "original_display", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Glas Reparatur", name: "glas_reparatur", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Lautsprecher", name: "lautsprecher", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "mikrofon", name: "mikrofon", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Vorderkamera", name: "vorderkamera", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Hauptkamera", name: "hauptkamera", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Kameraglas", name: "kameraglas", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Backcover", name: "backcover", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Rahmen", name: "rahmen", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Akku", name: "akku", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Ladebuchse", name: "ladebuchse", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Buttons", name: "buttons", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Software Update", name: "software_update", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean", required: false },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },          
        ]
      }