backend:
  name: git-gateway
  branch: main
media_folder: "static/content"
public_folder: "/content"
collections:
  ############### Single Pages ################
  - name: pages
    label: Pages
    files:
      ############### Homepage ################
      - name: home
        label: Home
        file: "/content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }

  ############### Smartphone Hersteller ################
  - name: smartphone-hersteller
    label: Smartphone Hersteller
    folder: /content/smartphone-hersteller
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }

  ############### Smartphones ################
  - name: smartphones
    label: Smartphones
    folder: /content/smartphone
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Modell", name: "name", widget: "string" }
      - { label: "Hersteller", name: "manufacturer", widget: "string" }
      - { label: "Services", name: "services", widget: "object", fields: [
          { label: "Analyse", name: "analyse", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean" },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          { label: "Wasserschaden", name: "wasserschaden", widget: "object", fields: [
              { label: "Enabled", name: "enabled", widget: "boolean" },
              { label: "Preis", name: "price", widget: "string" },
              { label: "Beschreibung", name: description, widget: "string"}
            ]
          },
          # Add fields for other services as needed
        ]
      }

  
  ############### Tablet Hersteller ################
  - name: tablet-hersteller
    label: Tablet Hersteller
    folder: /content/tablet-hersteller
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
  ############### Tablets ################
  - name: tablets
    label: Tablets
    folder: /content/tablet
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Modell", name: "name", widget: "string" }
      - { label: "Hersteller", name: "manufacturer", widget: "string" }